# Generated by Django 6.0.4 on 2026-04-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TattooWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('color', 'Цветная'), ('bw', 'Ч/б'), ('geometry', 'Геометрия'), ('realism', 'Реализм'), ('minimalism', 'Минимализм')], max_length=20)),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
    ]
