# Generated by Django 6.0.4 on 2026-04-14 19:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoowork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tattoowork',
            name='category',
            field=models.CharField(choices=[('color', 'Цветная тату'), ('bw', 'Чёрно-белая'), ('geometry', 'Геометрия'), ('realism', 'Реализм'), ('minimalism', 'Минимализм')], max_length=20),
        ),
    ]
